name: 🚀 Deploy Vite app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # 👇 opcional (recomendado pra testar o futuro)
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # 📥 Clona o repositório
      - name: Checkout
        uses: actions/checkout@v5

      # ⚙️ Configura Node
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"

      # 📦 Instala dependências
      - name: Install dependencies
        run: npm ci

      # 🏗️ Build do projeto
      - name: Build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ vars.VITE_GOOGLE_CLIENT_ID }}
        run: npm run build

      # 🧠 SPA fallback (EVITA 404 em refresh)
      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      # ⚙️ Configura GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 📦 Envia build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

        with:
          path: ./dist

      # 🚀 Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
